### ISSUE TITLE
看到Script但没有右边的配置

### ISSUE THREAD

**Issue by hiyoman1167** [zhangliwei7758/unity-AI-Chat-Toolkit#4]
大佬请问为什么我导入您的unitypackage打开sample场景之后只看到Script但没有右边的配置LLM的地方 代码编辑器中文显示乱码会影响吗? 感谢
![圖片](https://github.com/zhangliwei7758/unity-AI-Chat-Toolkit/assets/134185804/368625ae-d1cf-4e8f-bbd1-45d9f51fe74a)
![圖片](https://github.com/zhangliwei7758/unity-AI-Chat-Toolkit/assets/134185804/c806a0b5-cddf-42e3-b502-ba84f5cc1513)

**Comment by hiyoman1167** [comment]
请问可以提供全script UTF-8吗感谢? 我试了自己把每个script转回utp-8 没有乱码但还是找不到右边的配置LLM的地方

**Comment by rexainn** [comment]
请问你找到了吗？我遇到了同样的问题。

**Comment by zhanglv0209** [comment]
请问你找到了吗？我遇到了同样的问题。用的mac
